apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8sdocs-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /k8sdocs
        backend:
          serviceName: k8sdocs-svc
          servicePort: 80
