backend:
  name: super-backend
  replicaCount: 1
  image:
    repository: torklo/workshop-api
    tag: latest
  service:
    type: ClusterIP
    port: 80

frontend:
  name: super-frontend
  replicaCount: 1
  image:
    repository: torklo/workshop-frontend
    tag: latest
  service:
    type: LoadBalancer
    port: 80
  env:
    - name: BACKEND_URL
      value: 'http://super-backend'
