apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dockerdocs
  namespace: default
  labels:
    k8s-app: dockerdocs
spec:
  template:
    metadata:
      labels:
        k8s-app: dockerdocs
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: dockerdocs
        #image: docs/docker.github.io:latest
        image: ubuntu-k8s-1:30603/docker.github.io
