apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-deployment
  labels:
    app: docker-registry
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      nodeSelector:
        kubernetes.io/hostname: ubuntu-k8s-1
      containers:
      - name: docker-registry
        image: registry:2
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: dockerv
          mountPath: /var/lib/docker
      volumes:
      - name: dockerv
        persistentVolumeClaim:
          claimName: docker-registry-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: docker-registry-service
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
  - protocol: TCP
    targetPort: 5000
    port: 5000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  namespace: kube-system
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
